name: flutter_bin
description: "A Flutter plugin to retrieve metadata from binary files (executable files) on desktop platforms. Currently supports retrieving file version and other metadata on Windows."
version: 1.1.0
homepage: https://github.com/kihyun1998/flutter_bin
repository: https://github.com/kihyun1998/flutter_bin
issue_tracker: https://github.com/kihyun1998/xflutter_bin/issues
documentation: https://github.com/kihyun1998/flutter_bin/blob/main/README.md

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: FlutterBinPluginCApi
      macos:
        pluginClass: FlutterBinPlugin