name: flutter_bin
description: "A pure-Dart package to retrieve metadata (version, product name, and more) from binary files on desktop platforms. Supports Windows and macOS."
version: 3.1.0
homepage: https://github.com/kihyun1998/flutter_bin
repository: https://github.com/kihyun1998/flutter_bin
issue_tracker: https://github.com/kihyun1998/flutter_bin/issues
documentation: https://github.com/kihyun1998/flutter_bin/blob/main/README.md

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  ffi: ^2.1.0
  plist_parser: ^0.2.7
  path: ^1.9.1

dev_dependencies:
  test: ^1.25.0
  lints: ^5.0.0
